name: Compilar OS Engine HTML5ddd
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib run lime setup flixel
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install linc_luajit
          haxelib git hxCodec https://github.com/polybiusproxy/hxCodec
          haxelib git faxe https://github.com/uhobeisen/faxe
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webkit https://github.com/YoshiCrafter29/extension-webkit
          haxelib run lime setup

      - name: Compile Game (HTML5)
        run: haxelib run lime build html5 -release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OS-Engine-HTML5
          path: export/release/html5/bin/